// Game dimensions
export const GAME_WIDTH = 480;
export const GAME_HEIGHT = 640;

// Bird physics
export const GRAVITY = 0.3; // Reduced from 0.5 for a lighter feel
export const JUMP_STRENGTH = -6.5; // Adjusted from -8 to balance with new gravity
export const TERMINAL_VELOCITY = 8; // Caps maximum fall speed for better control
export const BIRD_WIDTH = 34; // Dimensions of a single sprite frame
export const BIRD_HEIGHT = 24; // Dimensions of a single sprite frame

// Bird sprite
export const BIRD_SPRITE_SRC = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAYCAYAAADb2_NjAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAIQSURBVEhL7ZdtS8NAFMb/SYtQ6iJaQdGFF/2DuhBl0YWLCoLu3CgoOrjYbbgIOuhf0EW3roIgCIIg6MLg4iC4iCD4k+Qk2WSSbPLJ9yeXOJk0L/c5997v/W8eQhgD5/N5vV7v9Xq5XC7/v6xYLE4mk2q12nU6/V6v91Kp1Gq1lEolhJD/D4jFYlRV5XK5/P39X6vVajabJUnS6/VKpZJpmgghqKurq/n5+SgKIoTwer3z8/Pj8fhyuRyLxaIoijAMl8v18vJyMBgURVEURVVVkiQhxDAMQwhxPB6/vLy8urqqqqpiGCYIArPZDAAuCALdbpcsy/1+n2VZURQhhFarxTAMQwhxPp+vVqsIIYIg6PV6pVLJsqxarQYApVLJNE0IId1uF0XRbrd3d3f1eh0hBHme5/P5mZmZWFlZkSSJruvPz88A4Pf7u7u7k5OTNE2DEOL7/V6v18PhkGU5Go2GYbjdbtM0kWW5XC6Pj4+z2SyEEMdxWZZleZ5hmLquK4ri+/2pVCoIAqfTyTAMz/O6rve+7/f7fbvdfo9hGIZh2u328fFxPp/3PG8YhiRJlWU5m80IIY7jcByXJAlRFGEYtm27rksI4TjO9/u93+8sy263W61WU1NTyWSSZVkI4XQ6TdMMw1AURSGEpmmWZX/4/X7f7/f9fn8ymeBzOO+cBQC+L5w/b5J2d/kFvAAAAABJRU5ErkJggg==';

// Sound effects
export const FLAP_SOUND_SRC = 'data:audio/wav;base64,UklGRigBAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQQAAAAgAQBE9f/79f/79v/2//T+7/7s/eT84vzV/ND8zPzP/M/90v3j/ub/AP8A/wD/APMA8gDyAPMA8gDwAO0A6gDnAOQA3wDfAN8A3QDcANoA1wDaANsA3QDeAOAA5ADoAOwA7gDwAPIA9AD1APcA+gD8AP4A/wAAAAAAAQACAAIAAgADAAQABQAGAAcACAAJAAoACwAMAA0ADgAPABAAEQASABMAFAAVABYAFwAYABkAGgAbABwAHQAeAB8AIAAhACIAIwAkACUAJgAnACgAKQAqACsALAAtAC4ALwAwADEAMgAzADQANQA2ADcAOAA5ADoAOwA8AD0APgA/AEAAQQBCAEMARABFAEYARwBIAEkASgBLAEwATQBOAE8AUABRAFIAUwBUAFUAVgBXAFgAWQBaAFsAXABdAF4AXwBgAGEAYgBjAGQAZQBmAGcAaABpAGoAawBsAG0AbgBvAHAAcQByAHMAdAB1AG8AdwB4AHkAegB7AHwAfQB+AH8AgACBAIIAgwCEAIUAhgCHAIgAiQCKAIwAjQCOAJAAkQCSAJMAlACVAJYAlwCYAJkAmgCbAJwAnQCeAJ8AoAChAKIAowCkAKUApgCnAKgAqQCrAKwArQCuAK8AsACxALMAtAC1ALYA">';

// Pipe settings
export const PIPE_WIDTH = 60;
export const PIPE_GAP = 180;
export const PIPE_SPEED = -3;
export const PIPE_SPAWN_INTERVAL = 100; // in frames

// Ground settings
export const GROUND_HEIGHT = 80;

// Particle settings
export const PARTICLE_COUNT = 30;
export const PARTICLE_GRAVITY = 0.05;
export const PARTICLE_FADE_RATE = 0.015;
export const PARTICLE_BASE_SPEED = 2;
